# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synchronize_skeletons_with_db_dialog.ui',
# licensing of 'synchronize_skeletons_with_db_dialog.ui' applies.
#
# Created: Thu Jan 30 11:47:09 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(645, 338)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.urlLineEdit = QtWidgets.QLineEdit(Dialog)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout_7.addWidget(self.urlLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.skeletonHorizontalLayout = QtWidgets.QHBoxLayout()
        self.skeletonHorizontalLayout.setObjectName("skeletonHorizontalLayout")
        self.skeletonLabel = QtWidgets.QLabel(self.widget)
        self.skeletonLabel.setObjectName("skeletonLabel")
        self.skeletonHorizontalLayout.addWidget(self.skeletonLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.skeletonHorizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.skeletonHorizontalLayout)
        self.skeletonDBTableWidget = QtWidgets.QTableWidget(self.widget)
        self.skeletonDBTableWidget.setColumnCount(2)
        self.skeletonDBTableWidget.setObjectName("skeletonDBTableWidget")
        self.skeletonDBTableWidget.setColumnCount(2)
        self.skeletonDBTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.skeletonDBTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skeletonDBTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.skeletonDBTableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selectAllDBButton = QtWidgets.QPushButton(self.widget)
        self.selectAllDBButton.setObjectName("selectAllDBButton")
        self.horizontalLayout_3.addWidget(self.selectAllDBButton)
        self.clearDBSelectionButton = QtWidgets.QPushButton(self.widget)
        self.clearDBSelectionButton.setObjectName("clearDBSelectionButton")
        self.horizontalLayout_3.addWidget(self.clearDBSelectionButton)
        self.downloadButton = QtWidgets.QPushButton(self.widget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_3.addWidget(self.downloadButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.skeletonLabel_2 = QtWidgets.QLabel(self.widget1)
        self.skeletonLabel_2.setObjectName("skeletonLabel_2")
        self.horizontalLayout_2.addWidget(self.skeletonLabel_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.skeletonLocalTableWidget = QtWidgets.QTableWidget(self.widget1)
        self.skeletonLocalTableWidget.setColumnCount(2)
        self.skeletonLocalTableWidget.setObjectName("skeletonLocalTableWidget")
        self.skeletonLocalTableWidget.setColumnCount(2)
        self.skeletonLocalTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.skeletonLocalTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skeletonLocalTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.skeletonLocalTableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectAllLocalButton = QtWidgets.QPushButton(self.widget1)
        self.selectAllLocalButton.setObjectName("selectAllLocalButton")
        self.horizontalLayout_4.addWidget(self.selectAllLocalButton)
        self.clearLocalSelectionButton = QtWidgets.QPushButton(self.widget1)
        self.clearLocalSelectionButton.setObjectName("clearLocalSelectionButton")
        self.horizontalLayout_4.addWidget(self.clearLocalSelectionButton)
        self.uploadButton = QtWidgets.QPushButton(self.widget1)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout_4.addWidget(self.uploadButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Synchronize Skeleton Defintions", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "URL", None, -1))
        self.skeletonLabel.setText(QtWidgets.QApplication.translate("Dialog", "Database", None, -1))
        self.skeletonDBTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Selected", None, -1))
        self.skeletonDBTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.selectAllDBButton.setText(QtWidgets.QApplication.translate("Dialog", "Select All", None, -1))
        self.clearDBSelectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear Selection", None, -1))
        self.downloadButton.setText(QtWidgets.QApplication.translate("Dialog", "Download", None, -1))
        self.skeletonLabel_2.setText(QtWidgets.QApplication.translate("Dialog", "Local Storage", None, -1))
        self.skeletonLocalTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Selected", None, -1))
        self.skeletonLocalTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.selectAllLocalButton.setText(QtWidgets.QApplication.translate("Dialog", "Select All", None, -1))
        self.clearLocalSelectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear Selection", None, -1))
        self.uploadButton.setText(QtWidgets.QApplication.translate("Dialog", "Upload", None, -1))

