# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\tool\GUI\layout\.\mg_state_machine_widget.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\tool\GUI\layout\.\mg_state_machine_widget.ui' applies.
#
# Created: Wed Jan 15 17:42:08 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MGStateMachineWidget(object):
    def setupUi(self, MGStateMachineWidget):
        MGStateMachineWidget.setObjectName("MGStateMachineWidget")
        MGStateMachineWidget.resize(604, 320)
        self.verticalLayout = QtWidgets.QVBoxLayout(MGStateMachineWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(MGStateMachineWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.stateDisplay = QtWidgets.QLabel(MGStateMachineWidget)
        self.stateDisplay.setObjectName("stateDisplay")
        self.horizontalLayout.addWidget(self.stateDisplay)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(MGStateMachineWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.animSpeedLineEdit = QtWidgets.QLineEdit(MGStateMachineWidget)
        self.animSpeedLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.animSpeedLineEdit.setObjectName("animSpeedLineEdit")
        self.horizontalLayout_2.addWidget(self.animSpeedLineEdit)
        self.label_3 = QtWidgets.QLabel(MGStateMachineWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(MGStateMachineWidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dirXLineEdit = QtWidgets.QLineEdit(MGStateMachineWidget)
        self.dirXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dirXLineEdit.setObjectName("dirXLineEdit")
        self.horizontalLayout_2.addWidget(self.dirXLineEdit)
        self.dirZLineEdit = QtWidgets.QLineEdit(MGStateMachineWidget)
        self.dirZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dirZLineEdit.setObjectName("dirZLineEdit")
        self.horizontalLayout_2.addWidget(self.dirZLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(MGStateMachineWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.blendWindowLineEdit = QtWidgets.QLineEdit(MGStateMachineWidget)
        self.blendWindowLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.blendWindowLineEdit.setObjectName("blendWindowLineEdit")
        self.horizontalLayout_3.addWidget(self.blendWindowLineEdit)
        self.activateIKCheckBox = QtWidgets.QCheckBox(MGStateMachineWidget)
        self.activateIKCheckBox.setChecked(True)
        self.activateIKCheckBox.setObjectName("activateIKCheckBox")
        self.horizontalLayout_3.addWidget(self.activateIKCheckBox)
        self.groundingCheckBox = QtWidgets.QCheckBox(MGStateMachineWidget)
        self.groundingCheckBox.setObjectName("groundingCheckBox")
        self.horizontalLayout_3.addWidget(self.groundingCheckBox)
        self.transitionConstraintCheckBox = QtWidgets.QCheckBox(MGStateMachineWidget)
        self.transitionConstraintCheckBox.setObjectName("transitionConstraintCheckBox")
        self.horizontalLayout_3.addWidget(self.transitionConstraintCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(MGStateMachineWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.posWeightLineEdit = QtWidgets.QLineEdit(MGStateMachineWidget)
        self.posWeightLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.posWeightLineEdit.setObjectName("posWeightLineEdit")
        self.horizontalLayout_4.addWidget(self.posWeightLineEdit)
        self.label_7 = QtWidgets.QLabel(MGStateMachineWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.dirWeightLineEdit = QtWidgets.QLineEdit(MGStateMachineWidget)
        self.dirWeightLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dirWeightLineEdit.setObjectName("dirWeightLineEdit")
        self.horizontalLayout_4.addWidget(self.dirWeightLineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(MGStateMachineWidget)
        QtCore.QMetaObject.connectSlotsByName(MGStateMachineWidget)

    def retranslateUi(self, MGStateMachineWidget):
        MGStateMachineWidget.setWindowTitle(QtWidgets.QApplication.translate("MGStateMachineWidget", "Form", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "State", None, -1))
        self.stateDisplay.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "StateName", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "speed", None, -1))
        self.animSpeedLineEdit.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "1", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "direction", None, -1))
        self.dirXLineEdit.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "0", None, -1))
        self.dirZLineEdit.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "-1", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "Blend window", None, -1))
        self.blendWindowLineEdit.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "20", None, -1))
        self.activateIKCheckBox.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "activate IK", None, -1))
        self.groundingCheckBox.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "activate grounding", None, -1))
        self.transitionConstraintCheckBox.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "transtion constraint", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "Position weight", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MGStateMachineWidget", "Direction weight", None, -1))

