# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\blend_animation_player_widget.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\blend_animation_player_widget.ui' applies.
#
# Created: Wed Jan 15 17:42:04 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(778, 516)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.animationControllerTableWidget = QtWidgets.QTableWidget(Form)
        self.animationControllerTableWidget.setColumnCount(2)
        self.animationControllerTableWidget.setObjectName("animationControllerTableWidget")
        self.animationControllerTableWidget.setColumnCount(2)
        self.animationControllerTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.animationControllerTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.animationControllerTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.animationControllerTableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.neighborLineEdit = QtWidgets.QLineEdit(Form)
        self.neighborLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.neighborLineEdit.setObjectName("neighborLineEdit")
        self.horizontalLayout.addWidget(self.neighborLineEdit)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.parameterSliderLayout = QtWidgets.QVBoxLayout()
        self.parameterSliderLayout.setObjectName("parameterSliderLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.parameterSliderLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.parameterSliderLayout)
        self.playerBar = QtWidgets.QHBoxLayout()
        self.playerBar.setObjectName("playerBar")
        self.animationButton = QtWidgets.QToolButton(Form)
        self.animationButton.setObjectName("animationButton")
        self.playerBar.addWidget(self.animationButton)
        self.animationFrameSlider = QtWidgets.QSlider(Form)
        self.animationFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationFrameSlider.setObjectName("animationFrameSlider")
        self.playerBar.addWidget(self.animationFrameSlider)
        self.animationFrameSpinBox = QtWidgets.QSpinBox(Form)
        self.animationFrameSpinBox.setObjectName("animationFrameSpinBox")
        self.playerBar.addWidget(self.animationFrameSpinBox)
        self.loopAnimationCheckBox = QtWidgets.QCheckBox(Form)
        self.loopAnimationCheckBox.setChecked(False)
        self.loopAnimationCheckBox.setObjectName("loopAnimationCheckBox")
        self.playerBar.addWidget(self.loopAnimationCheckBox)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.playerBar.addWidget(self.label_2)
        self.animationSpeedDoubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.animationSpeedDoubleSpinBox.setSingleStep(0.1)
        self.animationSpeedDoubleSpinBox.setProperty("value", 1.0)
        self.animationSpeedDoubleSpinBox.setObjectName("animationSpeedDoubleSpinBox")
        self.playerBar.addWidget(self.animationSpeedDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.playerBar.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.playerBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.drawModeComboBox = QtWidgets.QComboBox(Form)
        self.drawModeComboBox.setObjectName("drawModeComboBox")
        self.horizontalLayout_2.addWidget(self.drawModeComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveToFileButton = QtWidgets.QToolButton(Form)
        self.saveToFileButton.setObjectName("saveToFileButton")
        self.horizontalLayout_3.addWidget(self.saveToFileButton)
        self.exportToBVHButton = QtWidgets.QToolButton(Form)
        self.exportToBVHButton.setObjectName("exportToBVHButton")
        self.horizontalLayout_3.addWidget(self.exportToBVHButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.animationControllerTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "Name", None, -1))
        self.animationControllerTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Form", "Position", None, -1))
        self.neighborLineEdit.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Neighbors", None, -1))
        self.animationButton.setText(QtWidgets.QApplication.translate("Form", "Play", None, -1))
        self.loopAnimationCheckBox.setText(QtWidgets.QApplication.translate("Form", "Loop", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Speed", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Draw Mode", None, -1))
        self.saveToFileButton.setText(QtWidgets.QApplication.translate("Form", "Save To File", None, -1))
        self.exportToBVHButton.setText(QtWidgets.QApplication.translate("Form", "Export To BVH", None, -1))

