# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\copy_from_source_dialog.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\copy_from_source_dialog.ui' applies.
#
# Created: Wed Jan 15 17:42:05 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(909, 732)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.leftViewerLayout = QtWidgets.QGridLayout()
        self.leftViewerLayout.setObjectName("leftViewerLayout")
        self.verticalLayout_6.addLayout(self.leftViewerLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.leftDisplayFrameSlider = QtWidgets.QSlider(self.layoutWidget)
        self.leftDisplayFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftDisplayFrameSlider.setObjectName("leftDisplayFrameSlider")
        self.horizontalLayout_10.addWidget(self.leftDisplayFrameSlider)
        self.leftDisplayFrameSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.leftDisplayFrameSpinBox.setObjectName("leftDisplayFrameSpinBox")
        self.horizontalLayout_10.addWidget(self.leftDisplayFrameSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.leftStartFrameSlider = QtWidgets.QSlider(self.layoutWidget)
        self.leftStartFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftStartFrameSlider.setObjectName("leftStartFrameSlider")
        self.horizontalLayout_3.addWidget(self.leftStartFrameSlider)
        self.leftStartFrameSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.leftStartFrameSpinBox.setObjectName("leftStartFrameSpinBox")
        self.horizontalLayout_3.addWidget(self.leftStartFrameSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.leftEndFrameSlider = QtWidgets.QSlider(self.layoutWidget)
        self.leftEndFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftEndFrameSlider.setObjectName("leftEndFrameSlider")
        self.horizontalLayout_4.addWidget(self.leftEndFrameSlider)
        self.leftEndFrameSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.leftEndFrameSpinBox.setObjectName("leftEndFrameSpinBox")
        self.horizontalLayout_4.addWidget(self.leftEndFrameSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.rightViewerLayout = QtWidgets.QGridLayout()
        self.rightViewerLayout.setObjectName("rightViewerLayout")
        self.verticalLayout_5.addLayout(self.rightViewerLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.rightDisplayFrameSlider = QtWidgets.QSlider(self.layoutWidget)
        self.rightDisplayFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rightDisplayFrameSlider.setObjectName("rightDisplayFrameSlider")
        self.horizontalLayout_11.addWidget(self.rightDisplayFrameSlider)
        self.rightDisplayFrameSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.rightDisplayFrameSpinBox.setObjectName("rightDisplayFrameSpinBox")
        self.horizontalLayout_11.addWidget(self.rightDisplayFrameSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.rightStartFrameSlider = QtWidgets.QSlider(self.layoutWidget)
        self.rightStartFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rightStartFrameSlider.setObjectName("rightStartFrameSlider")
        self.horizontalLayout_5.addWidget(self.rightStartFrameSlider)
        self.rightStartFrameSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.rightStartFrameSpinBox.setObjectName("rightStartFrameSpinBox")
        self.horizontalLayout_5.addWidget(self.rightStartFrameSpinBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.rightEndFrameSlider = QtWidgets.QSlider(self.layoutWidget)
        self.rightEndFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rightEndFrameSlider.setObjectName("rightEndFrameSlider")
        self.horizontalLayout_14.addWidget(self.rightEndFrameSlider)
        self.rightEndFrameSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.rightEndFrameSpinBox.setObjectName("rightEndFrameSpinBox")
        self.horizontalLayout_14.addWidget(self.rightEndFrameSpinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.sceneObjectListWidget = QtWidgets.QListWidget(self.layoutWidget1)
        self.sceneObjectListWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.sceneObjectListWidget.setObjectName("sceneObjectListWidget")
        self.verticalLayout_4.addWidget(self.sceneObjectListWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.blendRangeLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.blendRangeLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.blendRangeLineEdit.setObjectName("blendRangeLineEdit")
        self.horizontalLayout_6.addWidget(self.blendRangeLineEdit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.selectAllJointsButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.selectAllJointsButton.setObjectName("selectAllJointsButton")
        self.horizontalLayout_12.addWidget(self.selectAllJointsButton)
        self.selectJointChildrenButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.selectJointChildrenButton.setObjectName("selectJointChildrenButton")
        self.horizontalLayout_12.addWidget(self.selectJointChildrenButton)
        self.deselectJointChildrenButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.deselectJointChildrenButton.setObjectName("deselectJointChildrenButton")
        self.horizontalLayout_12.addWidget(self.deselectJointChildrenButton)
        self.clearSelectedJointsButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.clearSelectedJointsButton.setObjectName("clearSelectedJointsButton")
        self.horizontalLayout_12.addWidget(self.clearSelectedJointsButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.jointTableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.jointTableWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.jointTableWidget.setColumnCount(2)
        self.jointTableWidget.setObjectName("jointTableWidget")
        self.jointTableWidget.setColumnCount(2)
        self.jointTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jointTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.jointTableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.copyButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout_2.addWidget(self.copyButton)
        self.selectButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Copy Parameters From Source", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Source", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Displayed Frame", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Src Start", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Src End", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Target", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "Displayed Frame", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Dest Start", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog", "Dest End", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Scene objects", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Blend Range", None, -1))
        self.blendRangeLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "20", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "Joint List", None, -1))
        self.selectAllJointsButton.setText(QtWidgets.QApplication.translate("Dialog", "Select All", None, -1))
        self.selectJointChildrenButton.setText(QtWidgets.QApplication.translate("Dialog", "Select Children", None, -1))
        self.deselectJointChildrenButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear Children", None, -1))
        self.clearSelectedJointsButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear All", None, -1))
        self.jointTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Selected", None, -1))
        self.jointTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.copyButton.setText(QtWidgets.QApplication.translate("Dialog", "Copy", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("Dialog", "Accept", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

