# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\mg_player_widget.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\mg_player_widget.ui' applies.
#
# Created: Wed Jan 15 17:42:08 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1016, 524)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generateRandomButton = QtWidgets.QToolButton(self.groupBox_2)
        self.generateRandomButton.setObjectName("generateRandomButton")
        self.horizontalLayout.addWidget(self.generateRandomButton)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.elementaryActionComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.elementaryActionComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.elementaryActionComboBox.setObjectName("elementaryActionComboBox")
        self.horizontalLayout.addWidget(self.elementaryActionComboBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.motionPrimitiveComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.motionPrimitiveComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.motionPrimitiveComboBox.setObjectName("motionPrimitiveComboBox")
        self.horizontalLayout.addWidget(self.motionPrimitiveComboBox)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mpStepsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.mpStepsLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.mpStepsLineEdit.setObjectName("mpStepsLineEdit")
        self.horizontalLayout.addWidget(self.mpStepsLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.generateConstrainedButton = QtWidgets.QToolButton(self.groupBox)
        self.generateConstrainedButton.setObjectName("generateConstrainedButton")
        self.horizontalLayout_2.addWidget(self.generateConstrainedButton)
        self.setConstraintsButton = QtWidgets.QToolButton(self.groupBox)
        self.setConstraintsButton.setObjectName("setConstraintsButton")
        self.horizontalLayout_2.addWidget(self.setConstraintsButton)
        self.clearGraphWalkButton = QtWidgets.QToolButton(self.groupBox)
        self.clearGraphWalkButton.setObjectName("clearGraphWalkButton")
        self.horizontalLayout_2.addWidget(self.clearGraphWalkButton)
        self.setConfigButton = QtWidgets.QToolButton(self.groupBox)
        self.setConfigButton.setObjectName("setConfigButton")
        self.horizontalLayout_2.addWidget(self.setConfigButton)
        self.saveConstraintsButton = QtWidgets.QToolButton(self.groupBox)
        self.saveConstraintsButton.setObjectName("saveConstraintsButton")
        self.horizontalLayout_2.addWidget(self.saveConstraintsButton)
        self.loadConstraintsButton = QtWidgets.QToolButton(self.groupBox)
        self.loadConstraintsButton.setObjectName("loadConstraintsButton")
        self.horizontalLayout_2.addWidget(self.loadConstraintsButton)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.randomSeedLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.randomSeedLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.randomSeedLineEdit.setObjectName("randomSeedLineEdit")
        self.horizontalLayout_2.addWidget(self.randomSeedLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.actionListWidget = QtWidgets.QListWidget(self.groupBox)
        self.actionListWidget.setObjectName("actionListWidget")
        self.verticalLayout_2.addWidget(self.actionListWidget)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.labelView = TimeLineLabelView(Form)
        self.labelView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelView.setObjectName("labelView")
        self.verticalLayout_4.addWidget(self.labelView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animationToggleButton = QtWidgets.QToolButton(Form)
        self.animationToggleButton.setObjectName("animationToggleButton")
        self.horizontalLayout_4.addWidget(self.animationToggleButton)
        self.animationFrameSlider = QtWidgets.QSlider(Form)
        self.animationFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationFrameSlider.setObjectName("animationFrameSlider")
        self.horizontalLayout_4.addWidget(self.animationFrameSlider)
        self.animationFrameSpinBox = QtWidgets.QSpinBox(Form)
        self.animationFrameSpinBox.setObjectName("animationFrameSpinBox")
        self.horizontalLayout_4.addWidget(self.animationFrameSpinBox)
        self.loopAnimationCheckBox = QtWidgets.QCheckBox(Form)
        self.loopAnimationCheckBox.setChecked(False)
        self.loopAnimationCheckBox.setObjectName("loopAnimationCheckBox")
        self.horizontalLayout_4.addWidget(self.loopAnimationCheckBox)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.animationSpeedDoubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.animationSpeedDoubleSpinBox.setSingleStep(0.1)
        self.animationSpeedDoubleSpinBox.setProperty("value", 1.0)
        self.animationSpeedDoubleSpinBox.setObjectName("animationSpeedDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.animationSpeedDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.fpsLineEdit = QtWidgets.QLineEdit(Form)
        self.fpsLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fpsLineEdit.setObjectName("fpsLineEdit")
        self.horizontalLayout_4.addWidget(self.fpsLineEdit)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.drawModeComboBox = QtWidgets.QComboBox(Form)
        self.drawModeComboBox.setObjectName("drawModeComboBox")
        self.horizontalLayout_6.addWidget(self.drawModeComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadGraphWalkButton = QtWidgets.QToolButton(Form)
        self.loadGraphWalkButton.setObjectName("loadGraphWalkButton")
        self.horizontalLayout_3.addWidget(self.loadGraphWalkButton)
        self.exportGraphWalkButton = QtWidgets.QToolButton(Form)
        self.exportGraphWalkButton.setObjectName("exportGraphWalkButton")
        self.horizontalLayout_3.addWidget(self.exportGraphWalkButton)
        self.exportButton = QtWidgets.QToolButton(Form)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_3.addWidget(self.exportButton)
        self.createCopyButton = QtWidgets.QToolButton(Form)
        self.createCopyButton.setObjectName("createCopyButton")
        self.horizontalLayout_3.addWidget(self.createCopyButton)
        self.createRagdollButton = QtWidgets.QToolButton(Form)
        self.createRagdollButton.setObjectName("createRagdollButton")
        self.horizontalLayout_3.addWidget(self.createRagdollButton)
        self.loadAnimatedMeshButton = QtWidgets.QToolButton(Form)
        self.loadAnimatedMeshButton.setObjectName("loadAnimatedMeshButton")
        self.horizontalLayout_3.addWidget(self.loadAnimatedMeshButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Random Synthesis", None, -1))
        self.generateRandomButton.setText(QtWidgets.QApplication.translate("Form", "Generate", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "ElementaryAction", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Motion Primitive", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "# Steps", None, -1))
        self.mpStepsLineEdit.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Constrained Synthesis", None, -1))
        self.generateConstrainedButton.setText(QtWidgets.QApplication.translate("Form", "Generate", None, -1))
        self.setConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Set Action Sequence", None, -1))
        self.clearGraphWalkButton.setText(QtWidgets.QApplication.translate("Form", "Clear Graph Walk", None, -1))
        self.setConfigButton.setText(QtWidgets.QApplication.translate("Form", "Set Config", None, -1))
        self.saveConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Save Constraints", None, -1))
        self.loadConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Load Constraints", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Seed", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Action Sequence", None, -1))
        self.animationToggleButton.setText(QtWidgets.QApplication.translate("Form", "Play", None, -1))
        self.loopAnimationCheckBox.setText(QtWidgets.QApplication.translate("Form", "Loop", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Speed", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.fpsLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "FPS", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Draw Mode", None, -1))
        self.loadGraphWalkButton.setText(QtWidgets.QApplication.translate("Form", "Load Graph Walk", None, -1))
        self.exportGraphWalkButton.setText(QtWidgets.QApplication.translate("Form", "Export Graph Walk", None, -1))
        self.exportButton.setText(QtWidgets.QApplication.translate("Form", "Export To BVH", None, -1))
        self.createCopyButton.setText(QtWidgets.QApplication.translate("Form", "Create Copy", None, -1))
        self.createRagdollButton.setText(QtWidgets.QApplication.translate("Form", "Create Ragdoll", None, -1))
        self.loadAnimatedMeshButton.setText(QtWidgets.QApplication.translate("Form", "Load Animated Mesh", None, -1))

from motion_analysis.gui.widgets.time_line_label_view import TimeLineLabelView
