# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\motion_modelling_dialog.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\motion_modelling_dialog.ui' applies.
#
# Created: Wed Jan 15 17:42:08 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 371)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.nameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.nameLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout_3.addWidget(self.nameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.splineBasisFactorLineEdit = QtWidgets.QLineEdit(Dialog)
        self.splineBasisFactorLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.splineBasisFactorLineEdit.setObjectName("splineBasisFactorLineEdit")
        self.horizontalLayout.addWidget(self.splineBasisFactorLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.selectAllJointsButton = QtWidgets.QPushButton(Dialog)
        self.selectAllJointsButton.setObjectName("selectAllJointsButton")
        self.horizontalLayout_12.addWidget(self.selectAllJointsButton)
        self.selectJointChildrenButton = QtWidgets.QPushButton(Dialog)
        self.selectJointChildrenButton.setObjectName("selectJointChildrenButton")
        self.horizontalLayout_12.addWidget(self.selectJointChildrenButton)
        self.deselectJointChildrenButton = QtWidgets.QPushButton(Dialog)
        self.deselectJointChildrenButton.setObjectName("deselectJointChildrenButton")
        self.horizontalLayout_12.addWidget(self.deselectJointChildrenButton)
        self.clearSelectedJointsButton = QtWidgets.QPushButton(Dialog)
        self.clearSelectedJointsButton.setObjectName("clearSelectedJointsButton")
        self.horizontalLayout_12.addWidget(self.clearSelectedJointsButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.jointTableWidget = QtWidgets.QTableWidget(Dialog)
        self.jointTableWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.jointTableWidget.setColumnCount(2)
        self.jointTableWidget.setObjectName("jointTableWidget")
        self.jointTableWidget.setColumnCount(2)
        self.jointTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jointTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jointTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.jointTableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.jointListLineEdit = QtWidgets.QLineEdit(Dialog)
        self.jointListLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jointListLineEdit.setText("")
        self.jointListLineEdit.setObjectName("jointListLineEdit")
        self.horizontalLayout_4.addWidget(self.jointListLineEdit)
        self.selectJointsFromStringButton = QtWidgets.QPushButton(Dialog)
        self.selectJointsFromStringButton.setObjectName("selectJointsFromStringButton")
        self.horizontalLayout_4.addWidget(self.selectJointsFromStringButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Create Statistical Motion Model", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Spine Basis Factor", None, -1))
        self.splineBasisFactorLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "20", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "Joint List", None, -1))
        self.selectAllJointsButton.setText(QtWidgets.QApplication.translate("Dialog", "Select All", None, -1))
        self.selectJointChildrenButton.setText(QtWidgets.QApplication.translate("Dialog", "Select Children", None, -1))
        self.deselectJointChildrenButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear Children", None, -1))
        self.clearSelectedJointsButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear All", None, -1))
        self.jointTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Selected", None, -1))
        self.jointTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Joint Filter List", None, -1))
        self.selectJointsFromStringButton.setText(QtWidgets.QApplication.translate("Dialog", "Update", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("Dialog", "Accept", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

