# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motion_db_browser_dialog.ui',
# licensing of 'motion_db_browser_dialog.ui' applies.
#
# Created: Thu Jan 30 16:49:10 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(859, 381)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.urlLineEdit = QtWidgets.QLineEdit(Dialog)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout_7.addWidget(self.urlLineEdit)
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_7.addWidget(self.statusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.skeletonHorizontalLayout = QtWidgets.QHBoxLayout()
        self.skeletonHorizontalLayout.setObjectName("skeletonHorizontalLayout")
        self.skeletonLabel = QtWidgets.QLabel(Dialog)
        self.skeletonLabel.setObjectName("skeletonLabel")
        self.skeletonHorizontalLayout.addWidget(self.skeletonLabel)
        self.skeletonListComboBox = QtWidgets.QComboBox(Dialog)
        self.skeletonListComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.skeletonListComboBox.setObjectName("skeletonListComboBox")
        self.skeletonHorizontalLayout.addWidget(self.skeletonListComboBox)
        self.newSkeletonButton = QtWidgets.QPushButton(Dialog)
        self.newSkeletonButton.setObjectName("newSkeletonButton")
        self.skeletonHorizontalLayout.addWidget(self.newSkeletonButton)
        self.deleteSkeletonButton = QtWidgets.QPushButton(Dialog)
        self.deleteSkeletonButton.setObjectName("deleteSkeletonButton")
        self.skeletonHorizontalLayout.addWidget(self.deleteSkeletonButton)
        self.replaceSkeletonButton = QtWidgets.QPushButton(Dialog)
        self.replaceSkeletonButton.setObjectName("replaceSkeletonButton")
        self.skeletonHorizontalLayout.addWidget(self.replaceSkeletonButton)
        self.loadSkeletonButton = QtWidgets.QPushButton(Dialog)
        self.loadSkeletonButton.setObjectName("loadSkeletonButton")
        self.skeletonHorizontalLayout.addWidget(self.loadSkeletonButton)
        self.exportSkeletonButton = QtWidgets.QPushButton(Dialog)
        self.exportSkeletonButton.setObjectName("exportSkeletonButton")
        self.skeletonHorizontalLayout.addWidget(self.exportSkeletonButton)
        self.editSkeletonButton = QtWidgets.QPushButton(Dialog)
        self.editSkeletonButton.setObjectName("editSkeletonButton")
        self.skeletonHorizontalLayout.addWidget(self.editSkeletonButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.skeletonHorizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.skeletonHorizontalLayout)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.collectionTreeWidget = QtWidgets.QTreeWidget(self.layoutWidget)
        self.collectionTreeWidget.setObjectName("collectionTreeWidget")
        self.verticalLayout.addWidget(self.collectionTreeWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.addCollectionButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addCollectionButton.setObjectName("addCollectionButton")
        self.horizontalLayout_6.addWidget(self.addCollectionButton)
        self.editCollectionButton = QtWidgets.QPushButton(self.layoutWidget)
        self.editCollectionButton.setObjectName("editCollectionButton")
        self.horizontalLayout_6.addWidget(self.editCollectionButton)
        self.deleteCollectionButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteCollectionButton.setObjectName("deleteCollectionButton")
        self.horizontalLayout_6.addWidget(self.deleteCollectionButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.clip_tab = QtWidgets.QWidget()
        self.clip_tab.setObjectName("clip_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.clip_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.processedMotionListWidget = QtWidgets.QListWidget(self.clip_tab)
        self.processedMotionListWidget.setObjectName("processedMotionListWidget")
        self.gridLayout.addWidget(self.processedMotionListWidget, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.selectButton = QtWidgets.QPushButton(self.clip_tab)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.deleteMotionButton = QtWidgets.QPushButton(self.clip_tab)
        self.deleteMotionButton.setObjectName("deleteMotionButton")
        self.horizontalLayout_2.addWidget(self.deleteMotionButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.importCollectionButton = QtWidgets.QPushButton(self.clip_tab)
        self.importCollectionButton.setObjectName("importCollectionButton")
        self.horizontalLayout_3.addWidget(self.importCollectionButton)
        self.exportCollectionButton = QtWidgets.QPushButton(self.clip_tab)
        self.exportCollectionButton.setObjectName("exportCollectionButton")
        self.horizontalLayout_3.addWidget(self.exportCollectionButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem5)
        self.alignMotionsButton = QtWidgets.QPushButton(self.clip_tab)
        self.alignMotionsButton.setObjectName("alignMotionsButton")
        self.horizontalLayout_32.addWidget(self.alignMotionsButton)
        self.gridLayout.addLayout(self.horizontalLayout_32, 3, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem6)
        self.setTimeFunctionButton = QtWidgets.QPushButton(self.clip_tab)
        self.setTimeFunctionButton.setObjectName("setTimeFunctionButton")
        self.horizontalLayout_34.addWidget(self.setTimeFunctionButton)
        self.editMotionsButton = QtWidgets.QPushButton(self.clip_tab)
        self.editMotionsButton.setObjectName("editMotionsButton")
        self.horizontalLayout_34.addWidget(self.editMotionsButton)
        self.retargetMotionsButton = QtWidgets.QPushButton(self.clip_tab)
        self.retargetMotionsButton.setObjectName("retargetMotionsButton")
        self.horizontalLayout_34.addWidget(self.retargetMotionsButton)
        self.copyMotionsButton = QtWidgets.QPushButton(self.clip_tab)
        self.copyMotionsButton.setObjectName("copyMotionsButton")
        self.horizontalLayout_34.addWidget(self.copyMotionsButton)
        self.gridLayout.addLayout(self.horizontalLayout_34, 4, 0, 1, 1)
        self.tabWidget.addTab(self.clip_tab, "")
        self.aligned_tab = QtWidgets.QWidget()
        self.aligned_tab.setObjectName("aligned_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.aligned_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.alignedMotionListWidget = QtWidgets.QListWidget(self.aligned_tab)
        self.alignedMotionListWidget.setObjectName("alignedMotionListWidget")
        self.verticalLayout_3.addWidget(self.alignedMotionListWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.selectAlignedMotionButton = QtWidgets.QPushButton(self.aligned_tab)
        self.selectAlignedMotionButton.setObjectName("selectAlignedMotionButton")
        self.horizontalLayout_8.addWidget(self.selectAlignedMotionButton)
        self.deleteAlignedMotionButton = QtWidgets.QPushButton(self.aligned_tab)
        self.deleteAlignedMotionButton.setObjectName("deleteAlignedMotionButton")
        self.horizontalLayout_8.addWidget(self.deleteAlignedMotionButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.createMotionModelButton = QtWidgets.QPushButton(self.aligned_tab)
        self.createMotionModelButton.setObjectName("createMotionModelButton")
        self.horizontalLayout_5.addWidget(self.createMotionModelButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.exportAlignedCollectionButton = QtWidgets.QPushButton(self.aligned_tab)
        self.exportAlignedCollectionButton.setObjectName("exportAlignedCollectionButton")
        self.horizontalLayout_4.addWidget(self.exportAlignedCollectionButton)
        self.retargetAlignedMotionsButton = QtWidgets.QPushButton(self.aligned_tab)
        self.retargetAlignedMotionsButton.setObjectName("retargetAlignedMotionsButton")
        self.horizontalLayout_4.addWidget(self.retargetAlignedMotionsButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.aligned_tab, "")
        self.model_tab = QtWidgets.QWidget()
        self.model_tab.setObjectName("model_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.model_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modelListWidget = QtWidgets.QListWidget(self.model_tab)
        self.modelListWidget.setObjectName("modelListWidget")
        self.gridLayout_2.addWidget(self.modelListWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.downloadMotionModelButton = QtWidgets.QPushButton(self.model_tab)
        self.downloadMotionModelButton.setObjectName("downloadMotionModelButton")
        self.horizontalLayout.addWidget(self.downloadMotionModelButton)
        self.deleteMotionModelButton = QtWidgets.QPushButton(self.model_tab)
        self.deleteMotionModelButton.setObjectName("deleteMotionModelButton")
        self.horizontalLayout.addWidget(self.deleteMotionModelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem11)
        self.importMotionModelButton = QtWidgets.QPushButton(self.model_tab)
        self.importMotionModelButton.setObjectName("importMotionModelButton")
        self.horizontalLayout_33.addWidget(self.importMotionModelButton)
        self.exportMotionModelButton = QtWidgets.QPushButton(self.model_tab)
        self.exportMotionModelButton.setObjectName("exportMotionModelButton")
        self.horizontalLayout_33.addWidget(self.exportMotionModelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_33, 2, 0, 1, 1)
        self.horizontalLayout_323 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_323.setObjectName("horizontalLayout_323")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_323.addItem(spacerItem12)
        self.createClusterTreeButton = QtWidgets.QPushButton(self.model_tab)
        self.createClusterTreeButton.setObjectName("createClusterTreeButton")
        self.horizontalLayout_323.addWidget(self.createClusterTreeButton)
        self.exportClusterTreeJSONButton = QtWidgets.QPushButton(self.model_tab)
        self.exportClusterTreeJSONButton.setObjectName("exportClusterTreeJSONButton")
        self.horizontalLayout_323.addWidget(self.exportClusterTreeJSONButton)
        self.exportClusterTreePCKButton = QtWidgets.QPushButton(self.model_tab)
        self.exportClusterTreePCKButton.setObjectName("exportClusterTreePCKButton")
        self.horizontalLayout_323.addWidget(self.exportClusterTreePCKButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_323, 3, 0, 1, 1)
        self.tabWidget.addTab(self.model_tab, "")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem13)
        self.useComputeClusterCheckBox = QtWidgets.QCheckBox(Dialog)
        self.useComputeClusterCheckBox.setObjectName("useComputeClusterCheckBox")
        self.horizontalLayout_31.addWidget(self.useComputeClusterCheckBox)
        self.debugInfoButton = QtWidgets.QPushButton(Dialog)
        self.debugInfoButton.setObjectName("debugInfoButton")
        self.horizontalLayout_31.addWidget(self.debugInfoButton)
        self.exportDatabaseButton = QtWidgets.QPushButton(Dialog)
        self.exportDatabaseButton.setObjectName("exportDatabaseButton")
        self.horizontalLayout_31.addWidget(self.exportDatabaseButton)
        self.generateMGFromFIleButton = QtWidgets.QPushButton(Dialog)
        self.generateMGFromFIleButton.setObjectName("generateMGFromFIleButton")
        self.horizontalLayout_31.addWidget(self.generateMGFromFIleButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Motion Database Browser", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "URL", None, -1))
        self.statusLabel.setText(QtWidgets.QApplication.translate("Dialog", "Status", None, -1))
        self.skeletonLabel.setText(QtWidgets.QApplication.translate("Dialog", "Skeleton", None, -1))
        self.newSkeletonButton.setText(QtWidgets.QApplication.translate("Dialog", "New Skeleton", None, -1))
        self.deleteSkeletonButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete Skeleton", None, -1))
        self.replaceSkeletonButton.setText(QtWidgets.QApplication.translate("Dialog", "Replace Skeleton", None, -1))
        self.loadSkeletonButton.setText(QtWidgets.QApplication.translate("Dialog", "Load Skeleton into Scene", None, -1))
        self.exportSkeletonButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Skeleton", None, -1))
        self.editSkeletonButton.setText(QtWidgets.QApplication.translate("Dialog", "Edit Skeleton", None, -1))
        self.collectionTreeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.collectionTreeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("Dialog", "Type", None, -1))
        self.addCollectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Add Collection", None, -1))
        self.editCollectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Edit Collection", None, -1))
        self.deleteCollectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete Collection", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("Dialog", "Load Selected Motions into Scene", None, -1))
        self.deleteMotionButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete Selected Motions", None, -1))
        self.importCollectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Import Collection from Folder", None, -1))
        self.exportCollectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Collection To Folder", None, -1))
        self.alignMotionsButton.setText(QtWidgets.QApplication.translate("Dialog", "Align Motion Clips", None, -1))
        self.setTimeFunctionButton.setText(QtWidgets.QApplication.translate("Dialog", "Set Time Function", None, -1))
        self.editMotionsButton.setText(QtWidgets.QApplication.translate("Dialog", "Edit Selected Motions", None, -1))
        self.retargetMotionsButton.setText(QtWidgets.QApplication.translate("Dialog", "Retarget Selected Motions", None, -1))
        self.copyMotionsButton.setText(QtWidgets.QApplication.translate("Dialog", "Copy Selected Motions", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clip_tab), QtWidgets.QApplication.translate("Dialog", "Motion Clips", None, -1))
        self.selectAlignedMotionButton.setText(QtWidgets.QApplication.translate("Dialog", "Load Selected Motions into Scene", None, -1))
        self.deleteAlignedMotionButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete Selected Motions", None, -1))
        self.createMotionModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Create Motion Model", None, -1))
        self.exportAlignedCollectionButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Collection", None, -1))
        self.retargetAlignedMotionsButton.setText(QtWidgets.QApplication.translate("Dialog", "Retarget Selected Motions", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aligned_tab), QtWidgets.QApplication.translate("Dialog", "Aligned Motion Clips", None, -1))
        self.downloadMotionModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Load Motion Model into scene", None, -1))
        self.deleteMotionModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete Selected Model", None, -1))
        self.importMotionModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Import Motion Model", None, -1))
        self.exportMotionModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Motion Model", None, -1))
        self.createClusterTreeButton.setText(QtWidgets.QApplication.translate("Dialog", "Create Cluster Tree", None, -1))
        self.exportClusterTreeJSONButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Cluster Tree To JSON ", None, -1))
        self.exportClusterTreePCKButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Cluster Tree To Pickle ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model_tab), QtWidgets.QApplication.translate("Dialog", "Motion Models", None, -1))
        self.useComputeClusterCheckBox.setText(QtWidgets.QApplication.translate("Dialog", "Use Kubernetes", None, -1))
        self.debugInfoButton.setText(QtWidgets.QApplication.translate("Dialog", "Print Debug Info", None, -1))
        self.exportDatabaseButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Database To Folder", None, -1))
        self.generateMGFromFIleButton.setText(QtWidgets.QApplication.translate("Dialog", "Generate Morphable Graph ", None, -1))

