# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\mp_player_widget.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\mp_player_widget.ui' applies.
#
# Created: Wed Jan 15 17:42:09 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1072, 573)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.generateRandomSamplesButton = QtWidgets.QToolButton(self.groupBox_2)
        self.generateRandomSamplesButton.setObjectName("generateRandomSamplesButton")
        self.horizontalLayout_5.addWidget(self.generateRandomSamplesButton)
        self.generateTreeSamplesButton = QtWidgets.QToolButton(self.groupBox_2)
        self.generateTreeSamplesButton.setObjectName("generateTreeSamplesButton")
        self.horizontalLayout_5.addWidget(self.generateTreeSamplesButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.sampleOffsetLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sampleOffsetLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sampleOffsetLineEdit.setObjectName("sampleOffsetLineEdit")
        self.horizontalLayout_5.addWidget(self.sampleOffsetLineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.numSamplesLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.numSamplesLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.numSamplesLineEdit.setObjectName("numSamplesLineEdit")
        self.horizontalLayout_5.addWidget(self.numSamplesLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.generateRandomConstraintsButton = QtWidgets.QToolButton(self.groupBox_2)
        self.generateRandomConstraintsButton.setObjectName("generateRandomConstraintsButton")
        self.horizontalLayout_8.addWidget(self.generateRandomConstraintsButton)
        self.loadConstraintsButton = QtWidgets.QToolButton(self.groupBox_2)
        self.loadConstraintsButton.setObjectName("loadConstraintsButton")
        self.horizontalLayout_8.addWidget(self.loadConstraintsButton)
        self.reachConstraintsButton = QtWidgets.QToolButton(self.groupBox_2)
        self.reachConstraintsButton.setObjectName("reachConstraintsButton")
        self.horizontalLayout_8.addWidget(self.reachConstraintsButton)
        self.setConfigButton = QtWidgets.QToolButton(self.groupBox_2)
        self.setConfigButton.setObjectName("setConfigButton")
        self.horizontalLayout_8.addWidget(self.setConfigButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.frameNumberSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.frameNumberSpinBox.setObjectName("frameNumberSpinBox")
        self.horizontalLayout_2.addWidget(self.frameNumberSpinBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.jointComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.jointComboBox.setObjectName("jointComboBox")
        self.horizontalLayout.addWidget(self.jointComboBox)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.numConstraintsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.numConstraintsLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.numConstraintsLineEdit.setObjectName("numConstraintsLineEdit")
        self.horizontalLayout_7.addWidget(self.numConstraintsLineEdit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.labelView = TimeLineLabelView(Form)
        self.labelView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelView.setObjectName("labelView")
        self.verticalLayout.addWidget(self.labelView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.animationToggleButton = QtWidgets.QToolButton(Form)
        self.animationToggleButton.setObjectName("animationToggleButton")
        self.horizontalLayout_4.addWidget(self.animationToggleButton)
        self.animationFrameSlider = QtWidgets.QSlider(Form)
        self.animationFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationFrameSlider.setObjectName("animationFrameSlider")
        self.horizontalLayout_4.addWidget(self.animationFrameSlider)
        self.animationFrameSpinBox = QtWidgets.QSpinBox(Form)
        self.animationFrameSpinBox.setObjectName("animationFrameSpinBox")
        self.horizontalLayout_4.addWidget(self.animationFrameSpinBox)
        self.loopAnimationCheckBox = QtWidgets.QCheckBox(Form)
        self.loopAnimationCheckBox.setChecked(False)
        self.loopAnimationCheckBox.setObjectName("loopAnimationCheckBox")
        self.horizontalLayout_4.addWidget(self.loopAnimationCheckBox)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.animationSpeedDoubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.animationSpeedDoubleSpinBox.setSingleStep(0.1)
        self.animationSpeedDoubleSpinBox.setProperty("value", 1.0)
        self.animationSpeedDoubleSpinBox.setObjectName("animationSpeedDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.animationSpeedDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.fpsLineEdit = QtWidgets.QLineEdit(Form)
        self.fpsLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fpsLineEdit.setObjectName("fpsLineEdit")
        self.horizontalLayout_4.addWidget(self.fpsLineEdit)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.drawModeComboBox = QtWidgets.QComboBox(Form)
        self.drawModeComboBox.setObjectName("drawModeComboBox")
        self.horizontalLayout_6.addWidget(self.drawModeComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exportButton = QtWidgets.QToolButton(Form)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_3.addWidget(self.exportButton)
        self.createCopyButton = QtWidgets.QToolButton(Form)
        self.createCopyButton.setObjectName("createCopyButton")
        self.horizontalLayout_3.addWidget(self.createCopyButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Synthesis", None, -1))
        self.generateRandomSamplesButton.setText(QtWidgets.QApplication.translate("Form", "Generate Random Samples", None, -1))
        self.generateTreeSamplesButton.setText(QtWidgets.QApplication.translate("Form", "Generate Tree Samples", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Offset", None, -1))
        self.sampleOffsetLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Number", None, -1))
        self.numSamplesLineEdit.setText(QtWidgets.QApplication.translate("Form", "10", None, -1))
        self.generateRandomConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Generate Constraints", None, -1))
        self.loadConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "LoadConstraints", None, -1))
        self.reachConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Reach Constraints", None, -1))
        self.setConfigButton.setText(QtWidgets.QApplication.translate("Form", "Set Config", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Frame", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Joint", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Number", None, -1))
        self.numConstraintsLineEdit.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.animationToggleButton.setText(QtWidgets.QApplication.translate("Form", "Play", None, -1))
        self.loopAnimationCheckBox.setText(QtWidgets.QApplication.translate("Form", "Loop", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Speed", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.fpsLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "FPS", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Draw Mode", None, -1))
        self.exportButton.setText(QtWidgets.QApplication.translate("Form", "Export To BVH", None, -1))
        self.createCopyButton.setText(QtWidgets.QApplication.translate("Form", "Create Copy", None, -1))

from motion_analysis.gui.widgets.time_line_label_view import TimeLineLabelView
