# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'retarget_dialog.ui',
# licensing of 'retarget_dialog.ui' applies.
#
# Created: Thu Jan 30 12:08:57 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 514)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sceneObjectListWidget = QtWidgets.QListWidget(Dialog)
        self.sceneObjectListWidget.setObjectName("sceneObjectListWidget")
        self.verticalLayout.addWidget(self.sceneObjectListWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sourceModelComboBox = QtWidgets.QComboBox(Dialog)
        self.sourceModelComboBox.setObjectName("sourceModelComboBox")
        self.horizontalLayout_3.addWidget(self.sourceModelComboBox)
        self.editSourceSkeletonModel = QtWidgets.QPushButton(Dialog)
        self.editSourceSkeletonModel.setObjectName("editSourceSkeletonModel")
        self.horizontalLayout_3.addWidget(self.editSourceSkeletonModel)
        self.addNewSourceSkeletonModelButton = QtWidgets.QPushButton(Dialog)
        self.addNewSourceSkeletonModelButton.setObjectName("addNewSourceSkeletonModelButton")
        self.horizontalLayout_3.addWidget(self.addNewSourceSkeletonModelButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.targetModelComboBox = QtWidgets.QComboBox(Dialog)
        self.targetModelComboBox.setObjectName("targetModelComboBox")
        self.horizontalLayout_4.addWidget(self.targetModelComboBox)
        self.editTargetSkeletonModel = QtWidgets.QPushButton(Dialog)
        self.editTargetSkeletonModel.setObjectName("editTargetSkeletonModel")
        self.horizontalLayout_4.addWidget(self.editTargetSkeletonModel)
        self.addTartSkeletonModelButton = QtWidgets.QPushButton(Dialog)
        self.addTartSkeletonModelButton.setObjectName("addTartSkeletonModelButton")
        self.horizontalLayout_4.addWidget(self.addTartSkeletonModelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scaleLineEdit = QtWidgets.QLineEdit(Dialog)
        self.scaleLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.scaleLineEdit.setObjectName("scaleLineEdit")
        self.horizontalLayout.addWidget(self.scaleLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.startFrameSlider = QtWidgets.QSlider(Dialog)
        self.startFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.startFrameSlider.setObjectName("startFrameSlider")
        self.horizontalLayout_5.addWidget(self.startFrameSlider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.startFrameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.startFrameLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.startFrameLineEdit.setObjectName("startFrameLineEdit")
        self.horizontalLayout_5.addWidget(self.startFrameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.endFrameSlider = QtWidgets.QSlider(Dialog)
        self.endFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.endFrameSlider.setObjectName("endFrameSlider")
        self.horizontalLayout_6.addWidget(self.endFrameSlider)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.endFrameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.endFrameLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.endFrameLineEdit.setObjectName("endFrameLineEdit")
        self.horizontalLayout_6.addWidget(self.endFrameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Retarget Motion", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Source model", None, -1))
        self.editSourceSkeletonModel.setText(QtWidgets.QApplication.translate("Dialog", "Edit", None, -1))
        self.addNewSourceSkeletonModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Add New", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Target model", None, -1))
        self.editTargetSkeletonModel.setText(QtWidgets.QApplication.translate("Dialog", "Edit", None, -1))
        self.addTartSkeletonModelButton.setText(QtWidgets.QApplication.translate("Dialog", "Add New", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Scale", None, -1))
        self.scaleLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "1", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Start frame", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "End Frame", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("Dialog", "Select", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

