# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skeleton_editor_dialog.ui',
# licensing of 'skeleton_editor_dialog.ui' applies.
#
# Created: Mon Feb 10 17:26:19 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 503)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.viewerLayout = QtWidgets.QGridLayout()
        self.viewerLayout.setObjectName("viewerLayout")
        self.gridLayout.addLayout(self.viewerLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.nameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.nameLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout_8.addWidget(self.nameLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jointLabel = QtWidgets.QLabel(Dialog)
        self.jointLabel.setObjectName("jointLabel")
        self.horizontalLayout.addWidget(self.jointLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.jointMapComboBox = QtWidgets.QComboBox(Dialog)
        self.jointMapComboBox.setObjectName("jointMapComboBox")
        self.horizontalLayout.addWidget(self.jointMapComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.twistXLineEdit = QtWidgets.QLineEdit(Dialog)
        self.twistXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.twistXLineEdit.setObjectName("twistXLineEdit")
        self.horizontalLayout_7.addWidget(self.twistXLineEdit)
        self.twistYLineEdit = QtWidgets.QLineEdit(Dialog)
        self.twistYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.twistYLineEdit.setObjectName("twistYLineEdit")
        self.horizontalLayout_7.addWidget(self.twistYLineEdit)
        self.twistZLineEdit = QtWidgets.QLineEdit(Dialog)
        self.twistZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.twistZLineEdit.setObjectName("twistZLineEdit")
        self.horizontalLayout_7.addWidget(self.twistZLineEdit)
        self.applyTwistRotationButton = QtWidgets.QPushButton(Dialog)
        self.applyTwistRotationButton.setObjectName("applyTwistRotationButton")
        self.horizontalLayout_7.addWidget(self.applyTwistRotationButton)
        self.setOrthogonalTwistButton = QtWidgets.QPushButton(Dialog)
        self.setOrthogonalTwistButton.setObjectName("setOrthogonalTwistButton")
        self.horizontalLayout_7.addWidget(self.setOrthogonalTwistButton)
        self.flipTwistButton = QtWidgets.QPushButton(Dialog)
        self.flipTwistButton.setObjectName("flipTwistButton")
        self.horizontalLayout_7.addWidget(self.flipTwistButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.swingXLineEdit = QtWidgets.QLineEdit(Dialog)
        self.swingXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.swingXLineEdit.setObjectName("swingXLineEdit")
        self.horizontalLayout_5.addWidget(self.swingXLineEdit)
        self.swingYLineEdit = QtWidgets.QLineEdit(Dialog)
        self.swingYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.swingYLineEdit.setObjectName("swingYLineEdit")
        self.horizontalLayout_5.addWidget(self.swingYLineEdit)
        self.swingZLineEdit = QtWidgets.QLineEdit(Dialog)
        self.swingZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.swingZLineEdit.setObjectName("swingZLineEdit")
        self.horizontalLayout_5.addWidget(self.swingZLineEdit)
        self.applySwingRotationButton = QtWidgets.QPushButton(Dialog)
        self.applySwingRotationButton.setObjectName("applySwingRotationButton")
        self.horizontalLayout_5.addWidget(self.applySwingRotationButton)
        self.setOrthogonalSwingButton = QtWidgets.QPushButton(Dialog)
        self.setOrthogonalSwingButton.setObjectName("setOrthogonalSwingButton")
        self.horizontalLayout_5.addWidget(self.setOrthogonalSwingButton)
        self.flipSwingButton = QtWidgets.QPushButton(Dialog)
        self.flipSwingButton.setObjectName("flipSwingButton")
        self.horizontalLayout_5.addWidget(self.flipSwingButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setGuessButton = QtWidgets.QPushButton(Dialog)
        self.setGuessButton.setObjectName("setGuessButton")
        self.horizontalLayout_3.addWidget(self.setGuessButton)
        self.alignToUpAxisButton = QtWidgets.QPushButton(Dialog)
        self.alignToUpAxisButton.setObjectName("alignToUpAxisButton")
        self.horizontalLayout_3.addWidget(self.alignToUpAxisButton)
        self.flipZAxisButton = QtWidgets.QPushButton(Dialog)
        self.flipZAxisButton.setObjectName("flipZAxisButton")
        self.horizontalLayout_3.addWidget(self.flipZAxisButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.scaleLineEdit = QtWidgets.QLineEdit(Dialog)
        self.scaleLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.scaleLineEdit.setObjectName("scaleLineEdit")
        self.horizontalLayout_4.addWidget(self.scaleLineEdit)
        self.applyScaleButton = QtWidgets.QPushButton(Dialog)
        self.applyScaleButton.setObjectName("applyScaleButton")
        self.horizontalLayout_4.addWidget(self.applyScaleButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.aligningRootComboBox = QtWidgets.QComboBox(Dialog)
        self.aligningRootComboBox.setObjectName("aligningRootComboBox")
        self.horizontalLayout_6.addWidget(self.aligningRootComboBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.loadDefaultPoseButton = QtWidgets.QPushButton(Dialog)
        self.loadDefaultPoseButton.setObjectName("loadDefaultPoseButton")
        self.horizontalLayout_2.addWidget(self.loadDefaultPoseButton)
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Skeleton Editor", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.jointLabel.setText(QtWidgets.QApplication.translate("Dialog", "Selected Joint: None", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Joint Map", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Twist", None, -1))
        self.twistXLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.twistYLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.twistZLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.applyTwistRotationButton.setText(QtWidgets.QApplication.translate("Dialog", "Set", None, -1))
        self.setOrthogonalTwistButton.setText(QtWidgets.QApplication.translate("Dialog", "Set orthogonal", None, -1))
        self.flipTwistButton.setText(QtWidgets.QApplication.translate("Dialog", "Flip 180", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Swing", None, -1))
        self.swingXLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.swingYLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.swingZLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.applySwingRotationButton.setText(QtWidgets.QApplication.translate("Dialog", "Set", None, -1))
        self.setOrthogonalSwingButton.setText(QtWidgets.QApplication.translate("Dialog", "Set orthogonal", None, -1))
        self.flipSwingButton.setText(QtWidgets.QApplication.translate("Dialog", "Flip 180", None, -1))
        self.setGuessButton.setText(QtWidgets.QApplication.translate("Dialog", "Guess Coordinate System", None, -1))
        self.alignToUpAxisButton.setText(QtWidgets.QApplication.translate("Dialog", "Align to Up Axis", None, -1))
        self.flipZAxisButton.setText(QtWidgets.QApplication.translate("Dialog", "Flip Z Axis", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Scale", None, -1))
        self.scaleLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "1", None, -1))
        self.applyScaleButton.setText(QtWidgets.QApplication.translate("Dialog", "Apply", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Aligning Root Node", None, -1))
        self.loadDefaultPoseButton.setText(QtWidgets.QApplication.translate("Dialog", "Set Default Pose", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("Dialog", "Accept", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

