# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animation_editor_dialog.ui',
# licensing of 'animation_editor_dialog.ui' applies.
#
# Created: Fri Apr 24 23:10:35 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(778, 641)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.leftViewerLayout = QtWidgets.QGridLayout()
        self.leftViewerLayout.setObjectName("leftViewerLayout")
        self.gridLayout.addLayout(self.leftViewerLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.leftDisplayFrameSlider = QtWidgets.QSlider(Dialog)
        self.leftDisplayFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftDisplayFrameSlider.setObjectName("leftDisplayFrameSlider")
        self.horizontalLayout_10.addWidget(self.leftDisplayFrameSlider)
        self.leftDisplayFrameSpinBox = QtWidgets.QSpinBox(Dialog)
        self.leftDisplayFrameSpinBox.setObjectName("leftDisplayFrameSpinBox")
        self.horizontalLayout_10.addWidget(self.leftDisplayFrameSpinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.leftStartFrameSlider = QtWidgets.QSlider(Dialog)
        self.leftStartFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftStartFrameSlider.setObjectName("leftStartFrameSlider")
        self.horizontalLayout_3.addWidget(self.leftStartFrameSlider)
        self.leftStartFrameSpinBox = QtWidgets.QSpinBox(Dialog)
        self.leftStartFrameSpinBox.setObjectName("leftStartFrameSpinBox")
        self.horizontalLayout_3.addWidget(self.leftStartFrameSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.leftEndFrameSlider = QtWidgets.QSlider(Dialog)
        self.leftEndFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftEndFrameSlider.setObjectName("leftEndFrameSlider")
        self.horizontalLayout_4.addWidget(self.leftEndFrameSlider)
        self.leftEndFrameSpinBox = QtWidgets.QSpinBox(Dialog)
        self.leftEndFrameSpinBox.setObjectName("leftEndFrameSpinBox")
        self.horizontalLayout_4.addWidget(self.leftEndFrameSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jointLabel = QtWidgets.QLabel(Dialog)
        self.jointLabel.setObjectName("jointLabel")
        self.horizontalLayout.addWidget(self.jointLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.fixJointButton = QtWidgets.QPushButton(Dialog)
        self.fixJointButton.setObjectName("fixJointButton")
        self.horizontalLayout_7.addWidget(self.fixJointButton)
        self.translateJointButton = QtWidgets.QPushButton(Dialog)
        self.translateJointButton.setObjectName("translateJointButton")
        self.horizontalLayout_7.addWidget(self.translateJointButton)
        self.translateXLineEdit = QtWidgets.QLineEdit(Dialog)
        self.translateXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.translateXLineEdit.setObjectName("translateXLineEdit")
        self.horizontalLayout_7.addWidget(self.translateXLineEdit)
        self.translateYLineEdit = QtWidgets.QLineEdit(Dialog)
        self.translateYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.translateYLineEdit.setObjectName("translateYLineEdit")
        self.horizontalLayout_7.addWidget(self.translateYLineEdit)
        self.translateZLineEdit = QtWidgets.QLineEdit(Dialog)
        self.translateZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.translateZLineEdit.setObjectName("translateZLineEdit")
        self.horizontalLayout_7.addWidget(self.translateZLineEdit)
        self.applyConstraintsButton = QtWidgets.QPushButton(Dialog)
        self.applyConstraintsButton.setObjectName("applyConstraintsButton")
        self.horizontalLayout_7.addWidget(self.applyConstraintsButton)
        self.clearConstraintsButton = QtWidgets.QPushButton(Dialog)
        self.clearConstraintsButton.setObjectName("clearConstraintsButton")
        self.horizontalLayout_7.addWidget(self.clearConstraintsButton)
        self.ccdCheckBox = QtWidgets.QCheckBox(Dialog)
        self.ccdCheckBox.setChecked(True)
        self.ccdCheckBox.setObjectName("ccdCheckBox")
        self.horizontalLayout_7.addWidget(self.ccdCheckBox)
        self.collectConstraintsCheckBox = QtWidgets.QCheckBox(Dialog)
        self.collectConstraintsCheckBox.setChecked(False)
        self.collectConstraintsCheckBox.setObjectName("collectConstraintsCheckBox")
        self.horizontalLayout_7.addWidget(self.collectConstraintsCheckBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.rotateJointButton = QtWidgets.QPushButton(Dialog)
        self.rotateJointButton.setObjectName("rotateJointButton")
        self.horizontalLayout_5.addWidget(self.rotateJointButton)
        self.rotateXLineEdit = QtWidgets.QLineEdit(Dialog)
        self.rotateXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateXLineEdit.setObjectName("rotateXLineEdit")
        self.horizontalLayout_5.addWidget(self.rotateXLineEdit)
        self.rotateYLineEdit = QtWidgets.QLineEdit(Dialog)
        self.rotateYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateYLineEdit.setObjectName("rotateYLineEdit")
        self.horizontalLayout_5.addWidget(self.rotateYLineEdit)
        self.rotateZLineEdit = QtWidgets.QLineEdit(Dialog)
        self.rotateZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateZLineEdit.setObjectName("rotateZLineEdit")
        self.horizontalLayout_5.addWidget(self.rotateZLineEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.blendRangeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.blendRangeLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.blendRangeLineEdit.setObjectName("blendRangeLineEdit")
        self.horizontalLayout_5.addWidget(self.blendRangeLineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deleteAfterButton = QtWidgets.QPushButton(Dialog)
        self.deleteAfterButton.setObjectName("deleteAfterButton")
        self.horizontalLayout_6.addWidget(self.deleteAfterButton)
        self.deleteBeforeButton = QtWidgets.QPushButton(Dialog)
        self.deleteBeforeButton.setObjectName("deleteBeforeButton")
        self.horizontalLayout_6.addWidget(self.deleteBeforeButton)
        self.mirrorAnimationButton = QtWidgets.QPushButton(Dialog)
        self.mirrorAnimationButton.setObjectName("mirrorAnimationButton")
        self.horizontalLayout_6.addWidget(self.mirrorAnimationButton)
        self.concatenateButton = QtWidgets.QPushButton(Dialog)
        self.concatenateButton.setObjectName("concatenateButton")
        self.horizontalLayout_6.addWidget(self.concatenateButton)
        self.smoothFramesButton = QtWidgets.QPushButton(Dialog)
        self.smoothFramesButton.setObjectName("smoothFramesButton")
        self.horizontalLayout_6.addWidget(self.smoothFramesButton)
        self.smoothWindowSizeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.smoothWindowSizeLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.smoothWindowSizeLineEdit.setObjectName("smoothWindowSizeLineEdit")
        self.horizontalLayout_6.addWidget(self.smoothWindowSizeLineEdit)
        self.resampleButton = QtWidgets.QPushButton(Dialog)
        self.resampleButton.setObjectName("resampleButton")
        self.horizontalLayout_6.addWidget(self.resampleButton)
        self.resampleFactorLineEdit = QtWidgets.QLineEdit(Dialog)
        self.resampleFactorLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.resampleFactorLineEdit.setObjectName("resampleFactorLineEdit")
        self.horizontalLayout_6.addWidget(self.resampleFactorLineEdit)
        self.setFPSButton = QtWidgets.QPushButton(Dialog)
        self.setFPSButton.setObjectName("setFPSButton")
        self.horizontalLayout_6.addWidget(self.setFPSButton)
        self.fpsLineEdit = QtWidgets.QLineEdit(Dialog)
        self.fpsLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fpsLineEdit.setObjectName("fpsLineEdit")
        self.horizontalLayout_6.addWidget(self.fpsLineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.guessGroundHeightButton = QtWidgets.QPushButton(Dialog)
        self.guessGroundHeightButton.setObjectName("guessGroundHeightButton")
        self.horizontalLayout_8.addWidget(self.guessGroundHeightButton)
        self.moveToGroundButton = QtWidgets.QPushButton(Dialog)
        self.moveToGroundButton.setObjectName("moveToGroundButton")
        self.horizontalLayout_8.addWidget(self.moveToGroundButton)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.sourceGroundHeightLineEdit = QtWidgets.QLineEdit(Dialog)
        self.sourceGroundHeightLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sourceGroundHeightLineEdit.setObjectName("sourceGroundHeightLineEdit")
        self.horizontalLayout_8.addWidget(self.sourceGroundHeightLineEdit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.targetGroundHeightLineEdit = QtWidgets.QLineEdit(Dialog)
        self.targetGroundHeightLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.targetGroundHeightLineEdit.setObjectName("targetGroundHeightLineEdit")
        self.horizontalLayout_8.addWidget(self.targetGroundHeightLineEdit)
        self.detectFootContactsButton = QtWidgets.QPushButton(Dialog)
        self.detectFootContactsButton.setObjectName("detectFootContactsButton")
        self.horizontalLayout_8.addWidget(self.detectFootContactsButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.labelComboBox = QtWidgets.QComboBox(Dialog)
        self.labelComboBox.setObjectName("labelComboBox")
        self.horizontalLayout_9.addWidget(self.labelComboBox)
        self.setAnnotationStartButton = QtWidgets.QPushButton(Dialog)
        self.setAnnotationStartButton.setObjectName("setAnnotationStartButton")
        self.horizontalLayout_9.addWidget(self.setAnnotationStartButton)
        self.createAnnotationButton = QtWidgets.QPushButton(Dialog)
        self.createAnnotationButton.setObjectName("createAnnotationButton")
        self.horizontalLayout_9.addWidget(self.createAnnotationButton)
        self.removeAnnotationButton = QtWidgets.QPushButton(Dialog)
        self.removeAnnotationButton.setObjectName("removeAnnotationButton")
        self.horizontalLayout_9.addWidget(self.removeAnnotationButton)
        self.groundFeetButton = QtWidgets.QPushButton(Dialog)
        self.groundFeetButton.setObjectName("groundFeetButton")
        self.horizontalLayout_9.addWidget(self.groundFeetButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.contactLabelView = TimeLineLabelView(Dialog)
        self.contactLabelView.setMaximumSize(QtCore.QSize(16777215, 100))
        self.contactLabelView.setObjectName("contactLabelView")
        self.verticalLayout.addWidget(self.contactLabelView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.flipBlenderCoordinateSystemButton = QtWidgets.QPushButton(Dialog)
        self.flipBlenderCoordinateSystemButton.setObjectName("flipBlenderCoordinateSystemButton")
        self.horizontalLayout_2.addWidget(self.flipBlenderCoordinateSystemButton)
        self.exportCommandsButton = QtWidgets.QPushButton(Dialog)
        self.exportCommandsButton.setObjectName("exportCommandsButton")
        self.horizontalLayout_2.addWidget(self.exportCommandsButton)
        self.undoButton = QtWidgets.QPushButton(Dialog)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_2.addWidget(self.undoButton)
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Animation Editor", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Displayed Frame", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Edit Start", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Edit End", None, -1))
        self.jointLabel.setText(QtWidgets.QApplication.translate("Dialog", "Selected Joint: None", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "IK", None, -1))
        self.fixJointButton.setText(QtWidgets.QApplication.translate("Dialog", "Fix Joint", None, -1))
        self.translateJointButton.setText(QtWidgets.QApplication.translate("Dialog", "Translate Joint", None, -1))
        self.translateXLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.translateYLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.translateZLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.applyConstraintsButton.setText(QtWidgets.QApplication.translate("Dialog", "Apply", None, -1))
        self.clearConstraintsButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear", None, -1))
        self.ccdCheckBox.setText(QtWidgets.QApplication.translate("Dialog", "ccd", None, -1))
        self.collectConstraintsCheckBox.setText(QtWidgets.QApplication.translate("Dialog", "collect", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "FK", None, -1))
        self.rotateJointButton.setText(QtWidgets.QApplication.translate("Dialog", "Rotate Joint", None, -1))
        self.rotateXLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.rotateYLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.rotateZLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Blend Range", None, -1))
        self.blendRangeLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "20", None, -1))
        self.deleteAfterButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete After Slider", None, -1))
        self.deleteBeforeButton.setText(QtWidgets.QApplication.translate("Dialog", "Delete Before Slider", None, -1))
        self.mirrorAnimationButton.setText(QtWidgets.QApplication.translate("Dialog", "Mirror", None, -1))
        self.concatenateButton.setText(QtWidgets.QApplication.translate("Dialog", "Concatenate", None, -1))
        self.smoothFramesButton.setText(QtWidgets.QApplication.translate("Dialog", "Smooth", None, -1))
        self.smoothWindowSizeLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "15", None, -1))
        self.resampleButton.setText(QtWidgets.QApplication.translate("Dialog", "Resample", None, -1))
        self.resampleFactorLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "1", None, -1))
        self.setFPSButton.setText(QtWidgets.QApplication.translate("Dialog", "SetFPS", None, -1))
        self.fpsLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.guessGroundHeightButton.setText(QtWidgets.QApplication.translate("Dialog", "GuessGround", None, -1))
        self.moveToGroundButton.setText(QtWidgets.QApplication.translate("Dialog", "Move To Ground", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Source:", None, -1))
        self.sourceGroundHeightLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Target:", None, -1))
        self.targetGroundHeightLineEdit.setText(QtWidgets.QApplication.translate("Dialog", "0", None, -1))
        self.detectFootContactsButton.setText(QtWidgets.QApplication.translate("Dialog", "Detect Foot Contacts", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "Foot Contacts", None, -1))
        self.setAnnotationStartButton.setText(QtWidgets.QApplication.translate("Dialog", "Set Start Frame", None, -1))
        self.createAnnotationButton.setText(QtWidgets.QApplication.translate("Dialog", "Create Annotation", None, -1))
        self.removeAnnotationButton.setText(QtWidgets.QApplication.translate("Dialog", "Remove Annotation", None, -1))
        self.groundFeetButton.setText(QtWidgets.QApplication.translate("Dialog", "Apply Foot Grounding", None, -1))
        self.flipBlenderCoordinateSystemButton.setText(QtWidgets.QApplication.translate("Dialog", "Flip Blender Coordinate Systems", None, -1))
        self.exportCommandsButton.setText(QtWidgets.QApplication.translate("Dialog", "Export Commands", None, -1))
        self.undoButton.setText(QtWidgets.QApplication.translate("Dialog", "Undo", None, -1))
        self.selectButton.setText(QtWidgets.QApplication.translate("Dialog", "Accept", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

from tool.core.widgets.time_line_label_view import TimeLineLabelView
