# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\animation_editing_widget.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\animation_editing_widget.ui' applies.
#
# Created: Wed Jan 15 17:42:03 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 436)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deleteBeforeButton = QtWidgets.QToolButton(Form)
        self.deleteBeforeButton.setObjectName("deleteBeforeButton")
        self.horizontalLayout_3.addWidget(self.deleteBeforeButton)
        self.deleteAfterButton = QtWidgets.QToolButton(Form)
        self.deleteAfterButton.setObjectName("deleteAfterButton")
        self.horizontalLayout_3.addWidget(self.deleteAfterButton)
        self.translateFramesButton = QtWidgets.QToolButton(Form)
        self.translateFramesButton.setObjectName("translateFramesButton")
        self.horizontalLayout_3.addWidget(self.translateFramesButton)
        self.translateXLineEdit = QtWidgets.QLineEdit(Form)
        self.translateXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.translateXLineEdit.setObjectName("translateXLineEdit")
        self.horizontalLayout_3.addWidget(self.translateXLineEdit)
        self.translateYLineEdit = QtWidgets.QLineEdit(Form)
        self.translateYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.translateYLineEdit.setObjectName("translateYLineEdit")
        self.horizontalLayout_3.addWidget(self.translateYLineEdit)
        self.translateZLineEdit = QtWidgets.QLineEdit(Form)
        self.translateZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.translateZLineEdit.setObjectName("translateZLineEdit")
        self.horizontalLayout_3.addWidget(self.translateZLineEdit)
        self.rotateFramesButton = QtWidgets.QToolButton(Form)
        self.rotateFramesButton.setObjectName("rotateFramesButton")
        self.horizontalLayout_3.addWidget(self.rotateFramesButton)
        self.rotateXLineEdit = QtWidgets.QLineEdit(Form)
        self.rotateXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateXLineEdit.setObjectName("rotateXLineEdit")
        self.horizontalLayout_3.addWidget(self.rotateXLineEdit)
        self.rotateYLineEdit = QtWidgets.QLineEdit(Form)
        self.rotateYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateYLineEdit.setObjectName("rotateYLineEdit")
        self.horizontalLayout_3.addWidget(self.rotateYLineEdit)
        self.rotateZLineEdit = QtWidgets.QLineEdit(Form)
        self.rotateZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateZLineEdit.setObjectName("rotateZLineEdit")
        self.horizontalLayout_3.addWidget(self.rotateZLineEdit)
        self.concatenateButton = QtWidgets.QToolButton(Form)
        self.concatenateButton.setObjectName("concatenateButton")
        self.horizontalLayout_3.addWidget(self.concatenateButton)
        self.smoothWindowSizeLineEdit = QtWidgets.QLineEdit(Form)
        self.smoothWindowSizeLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.smoothWindowSizeLineEdit.setObjectName("smoothWindowSizeLineEdit")
        self.horizontalLayout_3.addWidget(self.smoothWindowSizeLineEdit)
        self.smoothFramesButton = QtWidgets.QToolButton(Form)
        self.smoothFramesButton.setObjectName("smoothFramesButton")
        self.horizontalLayout_3.addWidget(self.smoothFramesButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mirrorAnimationButton = QtWidgets.QToolButton(Form)
        self.mirrorAnimationButton.setObjectName("mirrorAnimationButton")
        self.horizontalLayout_2.addWidget(self.mirrorAnimationButton)
        self.guessGroundHeightButton = QtWidgets.QToolButton(Form)
        self.guessGroundHeightButton.setObjectName("guessGroundHeightButton")
        self.horizontalLayout_2.addWidget(self.guessGroundHeightButton)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.sourceGroundHeightLineEdit = QtWidgets.QLineEdit(Form)
        self.sourceGroundHeightLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sourceGroundHeightLineEdit.setObjectName("sourceGroundHeightLineEdit")
        self.horizontalLayout_2.addWidget(self.sourceGroundHeightLineEdit)
        self.targetGroundHeightLineEdit = QtWidgets.QLineEdit(Form)
        self.targetGroundHeightLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.targetGroundHeightLineEdit.setObjectName("targetGroundHeightLineEdit")
        self.horizontalLayout_2.addWidget(self.targetGroundHeightLineEdit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.moveToGroundButton = QtWidgets.QToolButton(Form)
        self.moveToGroundButton.setObjectName("moveToGroundButton")
        self.horizontalLayout_2.addWidget(self.moveToGroundButton)
        self.detectGroundContactButton = QtWidgets.QToolButton(Form)
        self.detectGroundContactButton.setObjectName("detectGroundContactButton")
        self.horizontalLayout_2.addWidget(self.detectGroundContactButton)
        self.applyFootConstraintsButton = QtWidgets.QToolButton(Form)
        self.applyFootConstraintsButton.setObjectName("applyFootConstraintsButton")
        self.horizontalLayout_2.addWidget(self.applyFootConstraintsButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addConstraintButton = QtWidgets.QToolButton(Form)
        self.addConstraintButton.setObjectName("addConstraintButton")
        self.horizontalLayout.addWidget(self.addConstraintButton)
        self.jointComboBox = QtWidgets.QComboBox(Form)
        self.jointComboBox.setObjectName("jointComboBox")
        self.horizontalLayout.addWidget(self.jointComboBox)
        self.clearConstraintsButton = QtWidgets.QToolButton(Form)
        self.clearConstraintsButton.setObjectName("clearConstraintsButton")
        self.horizontalLayout.addWidget(self.clearConstraintsButton)
        self.applyConstraintsButton = QtWidgets.QToolButton(Form)
        self.applyConstraintsButton.setObjectName("applyConstraintsButton")
        self.horizontalLayout.addWidget(self.applyConstraintsButton)
        self.undoEditButton = QtWidgets.QToolButton(Form)
        self.undoEditButton.setObjectName("undoEditButton")
        self.horizontalLayout.addWidget(self.undoEditButton)
        self.plotCheckBox = QtWidgets.QCheckBox(Form)
        self.plotCheckBox.setObjectName("plotCheckBox")
        self.horizontalLayout.addWidget(self.plotCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.constraintsTableWidget = QtWidgets.QTableWidget(Form)
        self.constraintsTableWidget.setColumnCount(3)
        self.constraintsTableWidget.setObjectName("constraintsTableWidget")
        self.constraintsTableWidget.setColumnCount(3)
        self.constraintsTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.constraintsTableWidget, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.jointRotationComboBox = QtWidgets.QComboBox(Form)
        self.jointRotationComboBox.setObjectName("jointRotationComboBox")
        self.horizontalLayout_4.addWidget(self.jointRotationComboBox)
        self.rotateJointXLineEdit = QtWidgets.QLineEdit(Form)
        self.rotateJointXLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateJointXLineEdit.setObjectName("rotateJointXLineEdit")
        self.horizontalLayout_4.addWidget(self.rotateJointXLineEdit)
        self.rotateJointYLineEdit = QtWidgets.QLineEdit(Form)
        self.rotateJointYLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateJointYLineEdit.setObjectName("rotateJointYLineEdit")
        self.horizontalLayout_4.addWidget(self.rotateJointYLineEdit)
        self.rotateJointZLineEdit = QtWidgets.QLineEdit(Form)
        self.rotateJointZLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rotateJointZLineEdit.setObjectName("rotateJointZLineEdit")
        self.horizontalLayout_4.addWidget(self.rotateJointZLineEdit)
        self.rotateJointButton = QtWidgets.QToolButton(Form)
        self.rotateJointButton.setObjectName("rotateJointButton")
        self.horizontalLayout_4.addWidget(self.rotateJointButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.deleteBeforeButton.setText(QtWidgets.QApplication.translate("Form", "Delete Before Slider", None, -1))
        self.deleteAfterButton.setText(QtWidgets.QApplication.translate("Form", "Delete After Slider", None, -1))
        self.translateFramesButton.setText(QtWidgets.QApplication.translate("Form", "Translate", None, -1))
        self.translateXLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.translateYLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.translateZLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rotateFramesButton.setText(QtWidgets.QApplication.translate("Form", "Rotate", None, -1))
        self.rotateXLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rotateYLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rotateZLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.concatenateButton.setText(QtWidgets.QApplication.translate("Form", "Concatenate", None, -1))
        self.smoothWindowSizeLineEdit.setText(QtWidgets.QApplication.translate("Form", "15", None, -1))
        self.smoothFramesButton.setText(QtWidgets.QApplication.translate("Form", "Smooth", None, -1))
        self.mirrorAnimationButton.setText(QtWidgets.QApplication.translate("Form", "Mirror Animation", None, -1))
        self.guessGroundHeightButton.setText(QtWidgets.QApplication.translate("Form", "GuessGround", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Target:", None, -1))
        self.sourceGroundHeightLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.targetGroundHeightLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Source:", None, -1))
        self.moveToGroundButton.setText(QtWidgets.QApplication.translate("Form", "Move To Ground", None, -1))
        self.detectGroundContactButton.setText(QtWidgets.QApplication.translate("Form", "Detect Ground Contacts", None, -1))
        self.applyFootConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Apply Foot Constraints", None, -1))
        self.addConstraintButton.setText(QtWidgets.QApplication.translate("Form", "Add Constraint", None, -1))
        self.clearConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Clear Constraints", None, -1))
        self.applyConstraintsButton.setText(QtWidgets.QApplication.translate("Form", "Apply Constraints", None, -1))
        self.undoEditButton.setText(QtWidgets.QApplication.translate("Form", "Undo Last Edit", None, -1))
        self.plotCheckBox.setText(QtWidgets.QApplication.translate("Form", "Plot", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Joint Rotation Offset", None, -1))
        self.rotateJointXLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rotateJointYLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rotateJointZLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rotateJointButton.setText(QtWidgets.QApplication.translate("Form", "Apply", None, -1))

