# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\character_widget.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\character_widget.ui' applies.
#
# Created: Wed Jan 15 17:42:04 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 167)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.bodyComboBox = QtWidgets.QComboBox(Form)
        self.bodyComboBox.setObjectName("bodyComboBox")
        self.horizontalLayout_4.addWidget(self.bodyComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.applyForceButton = QtWidgets.QPushButton(Form)
        self.applyForceButton.setObjectName("applyForceButton")
        self.horizontalLayout_2.addWidget(self.applyForceButton)
        self.forceXLineEdit = QtWidgets.QLineEdit(Form)
        self.forceXLineEdit.setObjectName("forceXLineEdit")
        self.horizontalLayout_2.addWidget(self.forceXLineEdit)
        self.forceYLineEdit = QtWidgets.QLineEdit(Form)
        self.forceYLineEdit.setObjectName("forceYLineEdit")
        self.horizontalLayout_2.addWidget(self.forceYLineEdit)
        self.forceZLineEdit = QtWidgets.QLineEdit(Form)
        self.forceZLineEdit.setObjectName("forceZLineEdit")
        self.horizontalLayout_2.addWidget(self.forceZLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.applyTorqueButton = QtWidgets.QPushButton(Form)
        self.applyTorqueButton.setObjectName("applyTorqueButton")
        self.horizontalLayout.addWidget(self.applyTorqueButton)
        self.torqueXLineEdit = QtWidgets.QLineEdit(Form)
        self.torqueXLineEdit.setObjectName("torqueXLineEdit")
        self.horizontalLayout.addWidget(self.torqueXLineEdit)
        self.torqueYLineEdit = QtWidgets.QLineEdit(Form)
        self.torqueYLineEdit.setObjectName("torqueYLineEdit")
        self.horizontalLayout.addWidget(self.torqueYLineEdit)
        self.torqueZLineEdit = QtWidgets.QLineEdit(Form)
        self.torqueZLineEdit.setObjectName("torqueZLineEdit")
        self.horizontalLayout.addWidget(self.torqueZLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.jointComboBox = QtWidgets.QComboBox(Form)
        self.jointComboBox.setObjectName("jointComboBox")
        self.horizontalLayout_3.addWidget(self.jointComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setAngularVelocityButton = QtWidgets.QPushButton(Form)
        self.setAngularVelocityButton.setObjectName("setAngularVelocityButton")
        self.horizontalLayout_5.addWidget(self.setAngularVelocityButton)
        self.angularVelocityXLineEdit = QtWidgets.QLineEdit(Form)
        self.angularVelocityXLineEdit.setObjectName("angularVelocityXLineEdit")
        self.horizontalLayout_5.addWidget(self.angularVelocityXLineEdit)
        self.angularVelocityYLineEdit = QtWidgets.QLineEdit(Form)
        self.angularVelocityYLineEdit.setObjectName("angularVelocityYLineEdit")
        self.horizontalLayout_5.addWidget(self.angularVelocityYLineEdit)
        self.angularVelocityZLineEdit = QtWidgets.QLineEdit(Form)
        self.angularVelocityZLineEdit.setObjectName("angularVelocityZLineEdit")
        self.horizontalLayout_5.addWidget(self.angularVelocityZLineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Body", None, -1))
        self.applyForceButton.setText(QtWidgets.QApplication.translate("Form", "Apply Force", None, -1))
        self.forceXLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.forceYLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.forceZLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.applyTorqueButton.setText(QtWidgets.QApplication.translate("Form", "Apply Torque", None, -1))
        self.torqueXLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.torqueYLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.torqueZLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Joint", None, -1))
        self.setAngularVelocityButton.setText(QtWidgets.QApplication.translate("Form", "Set Angular Velocity", None, -1))
        self.angularVelocityXLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.angularVelocityYLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.angularVelocityZLineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))

