# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\set_annotation_dialog.ui',
# licensing of 'D:\Research\physics\workspace\mosi_app_mgtools\motion_analysis\GUI\layout\.\set_annotation_dialog.ui' applies.
#
# Created: Wed Jan 15 17:42:11 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewerLayout = QtWidgets.QGridLayout()
        self.viewerLayout.setObjectName("viewerLayout")
        self.verticalLayout.addLayout(self.viewerLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.labelComboBox = QtWidgets.QComboBox(Dialog)
        self.labelComboBox.setObjectName("labelComboBox")
        self.horizontalLayout_3.addWidget(self.labelComboBox)
        self.removeButton = QtWidgets.QPushButton(Dialog)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_3.addWidget(self.removeButton)
        self.setColorButton = QtWidgets.QPushButton(Dialog)
        self.setColorButton.setObjectName("setColorButton")
        self.horizontalLayout_3.addWidget(self.setColorButton)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.labelLineEdit = QtWidgets.QLineEdit(Dialog)
        self.labelLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelLineEdit.setObjectName("labelLineEdit")
        self.horizontalLayout_3.addWidget(self.labelLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.labelView = TimeLineLabelView(Dialog)
        self.labelView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.labelView.setObjectName("labelView")
        self.verticalLayout.addWidget(self.labelView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.displayFrameSlider = QtWidgets.QSlider(Dialog)
        self.displayFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.displayFrameSlider.setObjectName("displayFrameSlider")
        self.horizontalLayout.addWidget(self.displayFrameSlider)
        self.displayFrameSpinBox = QtWidgets.QSpinBox(Dialog)
        self.displayFrameSpinBox.setObjectName("displayFrameSpinBox")
        self.horizontalLayout.addWidget(self.displayFrameSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.createSegmentButton = QtWidgets.QPushButton(Dialog)
        self.createSegmentButton.setObjectName("createSegmentButton")
        self.horizontalLayout_4.addWidget(self.createSegmentButton)
        self.removeSegmentButton = QtWidgets.QPushButton(Dialog)
        self.removeSegmentButton.setObjectName("removeSegmentButton")
        self.horizontalLayout_4.addWidget(self.removeSegmentButton)
        self.extendSegmentButton = QtWidgets.QPushButton(Dialog)
        self.extendSegmentButton.setObjectName("extendSegmentButton")
        self.horizontalLayout_4.addWidget(self.extendSegmentButton)
        self.splitSegmentsButton = QtWidgets.QPushButton(Dialog)
        self.splitSegmentsButton.setObjectName("splitSegmentsButton")
        self.horizontalLayout_4.addWidget(self.splitSegmentsButton)
        self.mergeSegmentsButton = QtWidgets.QPushButton(Dialog)
        self.mergeSegmentsButton.setObjectName("mergeSegmentsButton")
        self.horizontalLayout_4.addWidget(self.mergeSegmentsButton)
        self.setAnnotationStartButton = QtWidgets.QPushButton(Dialog)
        self.setAnnotationStartButton.setObjectName("setAnnotationStartButton")
        self.horizontalLayout_4.addWidget(self.setAnnotationStartButton)
        self.clearTimelineButton = QtWidgets.QPushButton(Dialog)
        self.clearTimelineButton.setObjectName("clearTimelineButton")
        self.horizontalLayout_4.addWidget(self.clearTimelineButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.plotJointsButton = QtWidgets.QPushButton(Dialog)
        self.plotJointsButton.setObjectName("plotJointsButton")
        self.horizontalLayout_5.addWidget(self.plotJointsButton)
        self.removeJointPlotButton = QtWidgets.QPushButton(Dialog)
        self.removeJointPlotButton.setObjectName("removeJointPlotButton")
        self.horizontalLayout_5.addWidget(self.removeJointPlotButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Annotation Editor", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Label", None, -1))
        self.removeButton.setText(QtWidgets.QApplication.translate("Dialog", "Remove", None, -1))
        self.setColorButton.setText(QtWidgets.QApplication.translate("Dialog", "Set Color", None, -1))
        self.addButton.setText(QtWidgets.QApplication.translate("Dialog", "Add Label", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Displayed Frame", None, -1))
        self.createSegmentButton.setText(QtWidgets.QApplication.translate("Dialog", "Create Segment", None, -1))
        self.removeSegmentButton.setText(QtWidgets.QApplication.translate("Dialog", "Remove Segment", None, -1))
        self.extendSegmentButton.setText(QtWidgets.QApplication.translate("Dialog", "Extend Segment", None, -1))
        self.splitSegmentsButton.setText(QtWidgets.QApplication.translate("Dialog", "Split Segment", None, -1))
        self.mergeSegmentsButton.setText(QtWidgets.QApplication.translate("Dialog", "Merge Segments", None, -1))
        self.setAnnotationStartButton.setText(QtWidgets.QApplication.translate("Dialog", "Set Segment Start", None, -1))
        self.clearTimelineButton.setText(QtWidgets.QApplication.translate("Dialog", "Clear Timeline", None, -1))
        self.plotJointsButton.setText(QtWidgets.QApplication.translate("Dialog", "Draw Joint Trajectories", None, -1))
        self.removeJointPlotButton.setText(QtWidgets.QApplication.translate("Dialog", "Remove Joint Trajectories", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("Dialog", "Ok", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))

from motion_analysis.gui.widgets.time_line_label_view import TimeLineLabelView
