
from .animation_editor_widget import AnimationEditorWidget
from .animation_player_widget import AnimationPlayerWidget
from .character_widget import CharacterWidget
from .figure_controller_widget import FigureControllerWidget
from .group_animation_controller_widget import GroupAnimationPlayerWidget
from .object_properties_widget import ObjectPropertiesWidget
from .animated_mesh_widget import AnimatedMeshWidget
from .animation_directory_widget import AnimationDirectoryWidget

